name: Check and build app

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-n-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle wrapper
        run: ./gradlew build --no-daemon
      - run: echo "🍏 This job's status is ${{ job.status }}."