name: Getting statistics on repo

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * *'

jobs:
  pr-statistics:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Getting open PRs count and put to measurements
        shell: bash
        run: |
          cd statistics
          ./get_prs.sh
          cat prs.csv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install InfluxDB CLI
        run: |
          curl -o influxdb2-cli.tar.gz https://dl.influxdata.com/influxdb/releases/influxdb2-client-2.7.3-linux-amd64.tar.gz
          mkdir influx && tar xvzf influxdb2-cli.tar.gz -C influx/
          sudo cp influx/influx /usr/local/bin/
      - name: Push data to InfluxDB
        run: |
          influx version
          cd $GITHUB_WORKSPACE/statistics
          influx write dryrun -b pr_statistics -f prs.csv \
            --header "#constant measurement,pull_requests" \
            --header "#datatype long,string,string,dateTime:RFC3339"
      - name: Commit report
        run: |
          git config --global user.name 'GitHub Automation'
          git config --global user.email 'github-automation@users.noreply.github.com'
          git add .
          git status
#          git commit -am "Updating measurements"
#          git push