name: Getting statistics on repo

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 14 * * *'

jobs:
  pr-statistics:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Getting open PRs count
        shell: bash
        run: |
          GITHUB_PRS_RESPONSE=$(curl -s \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${{ github.repository }}/pulls\?state\=open\&per_page\=100)
          
          GITHUB_PR_COUNT=$(echo "$GITHUB_PRS_RESPONSE" | jq '. | length')
          TIMESTAMP=$(date +%s)
          echo "pull_requests;$GITHUB_PR_COUNT;$TIMESTAMP"