name: Getting statistics on repo

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * *'

jobs:
  pr-statistics:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Getting open PRs count and put to measurements
        shell: bash
        run: |
          cd statistics
          ./get_prs.sh
          cat prs.csv
        env:
          GITHUB_TOKEN: {{ secrets.GITHUB_TOKEN }}
      - name: Setup InfluxDB
        uses: influxdata/influxdb-action@v3
        with:
          influxdb_version: latest
          influxdb_start: false
      - name: Push data to InfluxDB
        shell: bash
        run: |
          cd statistics
          ./upload_influx.sh
#      - name: Commit report
#        run: |
#          git config --global user.name 'GitHub Automation'
#          git config --global user.email 'github-automation@users.noreply.github.com'
#          git commit -am "Updating measurements"
#          git push